Repository neow3j/neow3j, pull requests merged in 2020-10, with the labels that each got.

#227 Convenience methods
  build.gradle
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/Nep5Token.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/NeoURITest.java
  contract/src/test/java/io/neow3j/contract/Nep5TokenTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/build.gradle
  core/src/main/java/io/neow3j/transaction/Signer.java
  core/src/main/java/io/neow3j/transaction/Witness.java
  core/src/test/java/io/neow3j/transaction/WitnessTest.java
  crypto/src/main/java/io/neow3j/crypto/ECKeyPair.java
  wallet/src/main/java/io/neow3j/wallet/Account.java
  wallet/src/main/java/io/neow3j/wallet/Bip39Account.java
  wallet/src/main/java/io/neow3j/wallet/Wallet.java
  wallet/src/test/java/io/neow3j/wallet/AccountTest.java
  wallet/src/test/java/io/neow3j/wallet/Bip39AccountTest.java
  wallet/src/test/java/io/neow3j/wallet/WalletTest.java
Labels: neo3, sdk

#235 Wrapper for non-fungible Tokens according to the NEP-11 standard
  compiler/src/test-integration/java/io/neow3j/compiler/BinaryTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ByteArrayTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java
  contract/src/main/java/io/neow3j/contract/NFToken.java
  contract/src/main/java/io/neow3j/contract/Nep5Token.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/main/java/io/neow3j/contract/Token.java
  contract/src/test/java/io/neow3j/contract/GasTokenTest.java
  contract/src/test/java/io/neow3j/contract/NFTokenTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/Nep5TokenTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TokenTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  contract/src/test/resources/responses/nft_balanceof.json
  contract/src/test/resources/responses/nft_decimals_0.json
  contract/src/test/resources/responses/nft_decimals_5.json
  contract/src/test/resources/responses/nft_ownerof.json
  contract/src/test/resources/responses/nft_ownerof_multiple.json
  contract/src/test/resources/responses/nft_properties.json
  contract/src/test/resources/responses/nft_tokensof.json
  core/src/main/java/io/neow3j/protocol/core/methods/response/ByteStringStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NFTokenProperties.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionAttribute.java
  core/src/test/java/io/neow3j/protocol/core/methods/response/StackItemTest.java
  utils/src/main/java/io/neow3j/contract/ContractParameter.java
  utils/src/test/java/io/neow3j/contract/ContractParameterTest.java
  wallet/src/main/java/io/neow3j/wallet/Wallet.java
Labels: feature, neo3, sdk

#242 Feature/gradle debug info
  build.gradle
  compiler/src/main/java/io/neow3j/compiler/CompilationUnit.java
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jCompileAction.java
  gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginOptions.java
  gradle-plugin/src/main/java/io/neow3j/devpack/gradle/Neow3jPluginUtils.java
  utils/src/main/java/io/neow3j/constants/InteropServiceCode.java
  utils/src/main/java/io/neow3j/io/BinaryReader.java
  wallet/src/main/java/io/neow3j/wallet/Wallet.java
Labels: feature, neo3
