Repository neow3j/neow3j, pull requests merged in 2021-06, with the labels that each got.

#568 Update trigger types
  compiler/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/constants/TriggerType.java
Labels: devpack, maintenance

#569 Changed method name from 'as' to 'to'
  compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/Block.java
  devpack/src/main/java/io/neow3j/devpack/ECPoint.java
  devpack/src/main/java/io/neow3j/devpack/Hash160.java
  devpack/src/main/java/io/neow3j/devpack/Hash256.java
  devpack/src/main/java/io/neow3j/devpack/StringLiteralHelper.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP17Payment.java
Labels: devpack, maintenance

#570 Update call flags
  compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/constants/CallFlags.java
Labels: devpack, maintenance

#574 Extend the possible casts when constructing a array contract param from `Object`s
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
Labels: maintenance, sdk

#573 Add toJson method for transaction
  core/src/main/java/io/neow3j/protocol/core/response/NeoWitness.java
  core/src/main/java/io/neow3j/protocol/core/response/Transaction.java
  core/src/main/java/io/neow3j/protocol/core/response/TransactionAttribute.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
Labels: sdk

#579 Fix for instance methods bug
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectsTest.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Labels: bug, devpack

#581 Correct witness scope serialization
  core/src/main/java/io/neow3j/protocol/core/response/TransactionSigner.java
  core/src/test/java/io/neow3j/protocol/core/RequestTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
Labels: bug, sdk

#580 RC3 Update
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/resources/responses/neoToken_getAccountState.json
  contract/src/test/resources/responses/neoToken_getAccountState_noBalance.json
  contract/src/test/resources/responses/neoToken_getAccountState_noVote.json
  core/src/main/java/io/neow3j/protocol/core/response/NeoAccountState.java
  core/src/main/java/io/neow3j/protocol/core/response/NeoGetAccountState.java
  core/src/main/java/io/neow3j/protocol/core/stackitem/StructStackItem.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
  test-tools/src/main/resources/test.properties
Labels: rc3

#582 Hash160 and Hash256 support in Storage and StorageMap
  compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest2.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest2.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageMap.java
Labels: devpack, feature

#584 Update method signature of onNep11Payment method
  compiler/src/test/java/io/neow3j/compiler/OnNEP11PaymentMethodTest.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnDeployment.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP11Payment.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnVerification.java
Labels: devpack, maintenance

#585 Update constants
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  core/src/main/java/io/neow3j/constants/NeoConstants.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
  devpack/src/main/java/io/neow3j/devpack/constants/NamedCurve.java
  devpack/src/main/java/io/neow3j/devpack/constants/Role.java
  devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Labels: maintenance

#588 permissions, trusts, groups
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/GasTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  compiler/src/test/java/io/neow3j/compiler/GroupManifestTest.java
  compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/GasToken.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/test-integration/java/io/neow3j/contract/ContractManagementIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/NameServiceIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Group.java
Labels: devpack, maintenance, sdk

#590 More on trusts and permissions
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java
Labels: devpack, maintenance

#592 Fix handling of wildcard in permissions and trusts.
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java
  compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java
Labels: bug, devpack

#593 Fix for manifest trust serialization
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  core/src/main/java/io/neow3j/protocol/core/response/ContractManifest.java
  core/src/test/java/io/neow3j/protocol/core/response/ContractManifestTest.java
Labels: bug, sdk

#595 MaxAttributes check and minor changes
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/TransactionBuilder.java
  core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
Labels: maintenance, sdk

#597 Standardize the formatting of the devpack's constant names
  .github/workflows/ci-cd.yml
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  devpack/src/main/java/io/neow3j/devpack/Block.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Hash160.java
  devpack/src/main/java/io/neow3j/devpack/Hash256.java
  devpack/src/main/java/io/neow3j/devpack/Transaction.java
  devpack/src/main/java/io/neow3j/devpack/constants/NamedCurve.java
  devpack/src/main/java/io/neow3j/devpack/constants/OracleResponseCode.java
  devpack/src/main/java/io/neow3j/devpack/constants/Role.java
  devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Labels: devpack, maintenance

#599 Fixes for failed tests on windows
  build.gradle
  compiler/src/test/java/io/neow3j/compiler/sourcelookup/DirectorySourceContainerTest.java
  contract/src/test-integration/java/io/neow3j/contract/ContractManagementIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  core/src/main/java/io/neow3j/utils/Await.java
  gradle-plugin/src/test/java/io/neow3j/devpack/gradle/Neow3jPluginUtilsTest.java
Labels: maintenance
