Repository neow3j/neow3j, pull requests merged in 2021-08, with the labels that each got.

#621 Change debug info default column numbers to 1
  compiler/src/main/java/io/neow3j/compiler/DebugInfo.java
Labels: devpack, maintenance

#587 Add storage getters that include conversion
  compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest2.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest2.java
  core/src/main/java/io/neow3j/script/OpCode.java
  devpack/src/main/java/io/neow3j/devpack/ByteString.java
  devpack/src/main/java/io/neow3j/devpack/Helper.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageContext.java
  devpack/src/main/java/io/neow3j/devpack/StorageMap.java
Labels: feature, devpack

#626 Replace String literal before compiling the contract.
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
  compiler/src/test-integration/java/io/neow3j/compiler/PlaceholderSubstitutionIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/PlaceholderSubstitutionTest.java
Labels: feature, devpack, safe to test

#627 TransactionBuilder rework
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/FungibleToken.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/NeoURI.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/test-integration/java/io/neow3j/contract/ContractManagementIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/FungibleTokenIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/IntegrationTestHelper.java
  contract/src/test-integration/java/io/neow3j/contract/NameServiceIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/NeoURIIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/PolicyContractIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/RoleManagementIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/NeoURITest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  core/src/main/java/io/neow3j/transaction/AccountSigner.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/TransactionBuilder.java
  core/src/main/java/io/neow3j/wallet/Account.java
  core/src/main/java/io/neow3j/wallet/Wallet.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jExpressIntegrationTest.java
  core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
  core/src/test/java/io/neow3j/wallet/AccountTest.java
Labels: sdk, maintenance

#624 Correct handling of static field variables
  compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoContractVariable.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/NeoModule.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/DivisibleNFTIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NFTIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  compiler/src/test/java/io/neow3j/compiler/StaticVariablesTest.java
Labels: bug, devpack

#630 Fix for serialisation of manifest permissions
  compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java
  core/src/main/java/io/neow3j/protocol/core/response/ContractManifest.java
  core/src/test/java/io/neow3j/protocol/core/response/ContractManifestTest.java
Labels: bug, devpack

#628 Add manifest structure to devpack
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectInheritedIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/List.java
  devpack/src/main/java/io/neow3j/devpack/Manifest.java
  devpack/src/main/java/io/neow3j/devpack/constants/ParameterType.java
Labels: devpack, maintenance

#634 Add transfer methods with hash instead of account as 'from' parameter
  contract/src/main/java/io/neow3j/contract/FungibleToken.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
Labels: feature, sdk
