Repository neow3j/neow3j, pull requests merged in 2021-09, with the labels that each got.

#637 Add cancel vote method
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/test-integration/java/io/neow3j/contract/IntegrationTestHelper.java
  contract/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
Labels: feature, sdk

#643 Add helper method for int to byte[] conversion
  compiler/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageContextIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/Helper.java
  devpack/src/main/java/io/neow3j/devpack/StorageContext.java
Labels: feature, devpack

#644 Test module
  build.gradle
  compiler/build.gradle
  compiler/src/main/java/io/neow3j/compiler/NeoModule.java
  compiler/src/test-integration/resources/node-config/dbft.config.json
  contract/build.gradle
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/test-integration/java/io/neow3j/contract/NameServiceIntegrationTest.java
  contract/src/test-integration/resources/NameService.manifest.json
  contract/src/test-integration/resources/NameService.nef
  contract/src/test-integration/resources/node-config/config.json
  contract/src/test-integration/resources/node-config/rpcserver.config.json
  contract/src/test-integration/resources/node-config/wallet.json
  core/build.gradle
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jExpressIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/resources/node-config/config.json
  core/src/test-integration/resources/node-config/configReadTests.json
  core/src/test-integration/resources/node-config/dbft.config.json
  core/src/test-integration/resources/node-config/rpcserver.config.json
  core/src/test-integration/resources/node-config/wallet.json
  devpack-test/build.gradle
  devpack-test/src/main/java/io/neow3j/test/ContainerParameterResolver.java
  devpack-test/src/main/java/io/neow3j/test/ContractParameterResolver.java
  devpack-test/src/main/java/io/neow3j/test/ContractTest.java
  devpack-test/src/main/java/io/neow3j/test/ContractTestExtension.java
  devpack-test/src/main/java/io/neow3j/test/Neow3jParameterResolver.java
  devpack-test/src/test-integration/java/io/neow3j/test/ExampleContract.java
  devpack-test/src/test-integration/java/io/neow3j/test/ExampleTest.java
  devpack-test/src/test-integration/resources/example.batch
  devpack-test/src/test-integration/resources/example.neo-express
  devpack/build.gradle
  settings.gradle
  test-tools/build.gradle
  test-tools/src/main/java/io/neow3j/test/NeoExpressConfig.java
  test-tools/src/main/java/io/neow3j/test/NeoExpressTestContainer.java
  test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java
  test-tools/src/main/java/io/neow3j/test/TestProperties.java
  test-tools/src/main/resources/default.neo-express
  test-tools/src/main/resources/neo-cli-config/config.json
  test-tools/src/main/resources/neo-cli-config/dbft.config.json
  test-tools/src/main/resources/neo-cli-config/oracle.config.json
  test-tools/src/main/resources/neo-cli-config/rpcserver.config.json
  test-tools/src/main/resources/neo-cli-config/wallet.json
  test-tools/src/main/resources/test.properties
Labels: feature
