Repository neow3j/neow3j, pull requests merged in 2021-03, with the labels that each got.

#438 Smart Contract Array Initialization
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/converters/ArraysConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ArithmeticOperatorsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ArraysConverterIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ByteArrayTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RelationalOperatorsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java
  compiler/src/test-integration/resources/responses/ArithmeticOperators/addAndIncrement.json
  compiler/src/test-integration/resources/responses/ArithmeticOperators/allAssignmentOperators.json
  compiler/src/test-integration/resources/responses/ArithmeticOperators/allOperators.json
  compiler/src/test-integration/resources/responses/ArithmeticOperators/decrementAndSubtract.json
  compiler/src/test-integration/resources/responses/ArithmeticOperators/incrementAndAdd.json
  compiler/src/test-integration/resources/responses/ArithmeticOperators/subtractAndDecrement.json
  compiler/src/test-integration/resources/responses/RelationalOperators/equalBooleans.json
  compiler/src/test-integration/resources/responses/RelationalOperators/equalLargeIntegers.json
  compiler/src/test-integration/resources/responses/RelationalOperators/equalLargeLongs.json
  compiler/src/test-integration/resources/responses/RelationalOperators/equalStrings.json
  compiler/src/test-integration/resources/responses/RelationalOperators/unequalBooleans.json
  compiler/src/test-integration/resources/responses/RelationalOperators/unequalSmallIntegers.json
  compiler/src/test-integration/resources/responses/RelationalOperators/unequalSmallLongs.json
  compiler/src/test/java/io/neow3j/compiler/CompilerTest.java
  devpack/src/main/java/io/neow3j/devpack/List.java
Labels: devpack, maintenance, neo3

#437 Name Service wrapper class
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/resources/responses/nft_ownerof.json
  contract/src/test/resources/responses/nns_getRecord_typeA.json
  contract/src/test/resources/responses/nns_getRecord_typeAAAA.json
  contract/src/test/resources/responses/nns_getRecord_typeCNAME.json
  contract/src/test/resources/responses/nns_getRecord_typeTXT.json
  contract/src/test/resources/responses/nns_invalidOperation_dueToState.json
  contract/src/test/resources/responses/nns_invokefunction_getPrice.json
  contract/src/test/resources/responses/nns_invokefunction_ownerof.json
  contract/src/test/resources/responses/nns_invokefunction_properties.json
  contract/src/test/resources/responses/nns_invokefunction_symbol.json
  contract/src/test/resources/responses/nns_invokefunction_totalSupply.json
  contract/src/test/resources/responses/nns_invokescript_addRoot.json
  contract/src/test/resources/responses/nns_returnAny.json
  core/src/main/java/io/neow3j/protocol/core/RecordType.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NameState.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TokenState.java
Labels: feature, neo3, preview5, sdk

#444 Added Hash256 class and adapted general usage of Hash160 and Hash256
  compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/VerificationMethodIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/constants/NeoConstants.java
  core/src/main/java/io/neow3j/contract/ContractParameter.java
  core/src/main/java/io/neow3j/contract/Hash160.java
  core/src/main/java/io/neow3j/contract/Hash256.java
  core/src/main/java/io/neow3j/contract/ScriptBuilder.java
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/core/Neo.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ContractManifest.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ContractMethodToken.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/InvocationResult.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoApplicationLog.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoBlock.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoBlockHash.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetContractState.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetMemPool.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetNep17Balances.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetNep17Transfers.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetRawMemPool.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoSendRawTransaction.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/Transaction.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionSendAsset.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionSigner.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/utils/Await.java
  core/src/main/java/io/neow3j/wallet/Account.java
  core/src/test-integration/java/io/neow3j/protocol/IntegrationTestHelper.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
  core/src/test/java/io/neow3j/contract/Hash160Test.java
  core/src/test/java/io/neow3j/contract/Hash256Test.java
  core/src/test/java/io/neow3j/protocol/core/RequestTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
Labels: devpack, neo3, sdk

#445 Refactoring of stack item API
  compiler/src/test-integration/java/io/neow3j/compiler/ArithmeticOperatorsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ArraysConverterIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/BinaryTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ByteArrayTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractInterfacesTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/DeploymentMethodIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/GasTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HelperTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/IteratorTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ListIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/MapTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectLengthTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RelationalOperatorsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StringLiteralHelperIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/VerificationMethodIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/AnyStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ArrayStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/BooleanStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/BufferStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ByteArrayStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ByteStringStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/IntegerStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/InteropInterfaceStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/ListLikeStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/MapStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/PointerStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/StackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/StructStackItem.java
  core/src/main/java/io/neow3j/protocol/exceptions/StackItemCastException.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/protocol/core/methods/response/StackItemTest.java
Labels: maintenance, neo3

#453 Reuse CallFlags values in devpack
  devpack/src/main/java/io/neow3j/devpack/CallFlags.java
Labels: devpack, maintenance, neo3

#457 Added methods for State Service RPC calls
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/core/Neo.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetProof.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetStateHeight.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetStateRoot.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoVerifyProof.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/RequestTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
Labels: feature, neo3, sdk

#459 Non-fungible token changes
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/resources/responses/nns_invokefunction_properties.json
  core/src/main/java/io/neow3j/protocol/core/methods/response/NFTokenState.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NameState.java
Labels: neo3, rc1, sdk

#460 Several RC1 changes for which we don't have a specific issue
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/test-integration/java/io/neow3j/compiler/AccountIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/BinaryTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RelationalOperatorsTest.java
  compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/GasToken.java
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/GasTokenTest.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/java/io/neow3j/contract/RoleManagementTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/constants/InteropServiceCode.java
  core/src/main/java/io/neow3j/constants/OpCode.java
  core/src/main/java/io/neow3j/contract/ScriptBuilder.java
  devpack/src/main/java/io/neow3j/devpack/Account.java
  devpack/src/main/java/io/neow3j/devpack/ExecutionEngine.java
  devpack/src/main/java/io/neow3j/devpack/OracleContract.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageFlag.java
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/GasToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/RoleManagement.java
Labels: neo3, rc1

#466 Removed outdated PolicyContract methods and added new NeoToken methods
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/resources/responses/invokefunction_getRegisterPrice.json
Labels: neo3, rc1, sdk

#477 Integration test config changes
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/resources/node-config/configReadTests.json
  core/src/test-integration/resources/node-config/dbft.config.json
  test-properties/src/main/java/io/neow3j/NeoTestContainer.java
Labels: feature, neo3, sdk

#475 Replace BlockParameter with BigInteger
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/protocol/core/BlockParameter.java
  core/src/main/java/io/neow3j/protocol/core/BlockParameterIndex.java
  core/src/main/java/io/neow3j/protocol/core/BlockParameterName.java
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/rx/JsonRpc2_0Rx.java
  core/src/main/java/io/neow3j/protocol/rx/Neow3jRx.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java
Labels: devpack, maintenance, neo3

#479 Add method to subscribe to new blocks without catching up
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/rx/JsonRpc2_0Rx.java
  core/src/main/java/io/neow3j/protocol/rx/Neow3jRx.java
  core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java
Labels: feature, neo3, sdk

#489 Add ByteString type
  compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HelperIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StringConcatenationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StringLiteralHelperIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java
  compiler/src/test/java/io/neow3j/compiler/ECPointTest.java
  compiler/src/test/java/io/neow3j/compiler/HashTest.java
  compiler/src/test/java/io/neow3j/compiler/StringLiteralHelperTest.java
  devpack/src/main/java/io/neow3j/devpack/ByteString.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Crypto.java
  devpack/src/main/java/io/neow3j/devpack/ECPoint.java
  devpack/src/main/java/io/neow3j/devpack/Hash160.java
  devpack/src/main/java/io/neow3j/devpack/Hash256.java
  devpack/src/main/java/io/neow3j/devpack/Helper.java
  devpack/src/main/java/io/neow3j/devpack/Iterator.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageContext.java
  devpack/src/main/java/io/neow3j/devpack/StorageMap.java
  devpack/src/main/java/io/neow3j/devpack/StringLiteralHelper.java
  devpack/src/main/java/io/neow3j/devpack/Transaction.java
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java
  devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/Role.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Labels: devpack, feature, neo n3

#490 Remove getContract from ContractManagement
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
Labels: neo n3, sdk
