Repository neow3j/neow3j, pull requests merged in 2021-05, with the labels that each got.

#491 Adapt interop services
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectInheritedIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java
  core/src/main/java/io/neow3j/constants/InteropService.java
  core/src/main/java/io/neow3j/contract/ScriptBuilder.java
  core/src/main/java/io/neow3j/contract/ScriptReader.java
  core/src/main/java/io/neow3j/transaction/VerificationScript.java
  core/src/test/java/io/neow3j/contract/Hash160Test.java
  core/src/test/java/io/neow3j/contract/ScriptBuilderTest.java
  core/src/test/java/io/neow3j/transaction/VerificationScriptTest.java
  core/src/test/java/io/neow3j/transaction/WitnessTest.java
  devpack/src/main/java/io/neow3j/devpack/Account.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Crypto.java
  devpack/src/main/java/io/neow3j/devpack/ExecutionEngine.java
  devpack/src/main/java/io/neow3j/devpack/Iterator.java
  devpack/src/main/java/io/neow3j/devpack/Runtime.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageContext.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Syscall.java
Labels: devpack, neo n3, rc2

#548 Empty catch with inner var init
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
Labels: bug, devpack

#545 javadoc and cleanups
  compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test-integration/java/io/neow3j/contract/NeoTokenIntegrationTest.java
  contract/src/test-integration/java/io/neow3j/contract/RoleManagementIntegrationTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  contract/src/test/resources/responses/invokefunction_returnIntOne.json
  contract/src/test/resources/responses/invokefunction_returnIntZero.json
  core/src/main/java/io/neow3j/contract/ScriptBuilder.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/protocol/Neow3j.java
  core/src/main/java/io/neow3j/protocol/Neow3jConfig.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoApplicationLog.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoBlockCount.java
  core/src/main/java/io/neow3j/protocol/core/polling/BlockPolling.java
  core/src/main/java/io/neow3j/protocol/rx/JsonRpc2_0Rx.java
  core/src/main/java/io/neow3j/transaction/InvocationScript.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/VerificationScript.java
  core/src/main/java/io/neow3j/transaction/Witness.java
  core/src/main/java/io/neow3j/utils/AddressUtils.java
  core/src/main/java/io/neow3j/utils/Await.java
  core/src/main/java/io/neow3j/utils/Numeric.java
  core/src/main/java/io/neow3j/wallet/Account.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/protocol/rx/JsonRpc2_0RxTest.java
  core/src/test/java/io/neow3j/transaction/WitnessTest.java
  core/src/test/java/io/neow3j/utils/NumericTest.java
  devpack/src/main/java/io/neow3j/devpack/ByteString.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Runtime.java
Labels: maintenance

#551 Fix string switch case bug
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java
Labels: bug, devpack

#555 Make Contract Parameter Constructor protected
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/main/java/io/neow3j/compiler/NeoEvent.java
  compiler/src/test/java/io/neow3j/compiler/ContractEventsTest.java
  contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
Labels: maintenance

#554 Make getHash of Contract Interfaces return little-endian hash
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractInterfacesIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/GasTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  devpack/src/main/java/io/neow3j/devpack/ContractInterface.java
  devpack/src/main/java/io/neow3j/devpack/Hash160.java
  devpack/src/main/java/io/neow3j/devpack/Runtime.java
Labels: maintenance

#557 Restructuring in the devpack
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractInterfacesIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/InstanceOfIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/IteratorTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectInheritedIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RuntimeIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Runtime.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/annotations/ContractHash.java
  devpack/src/main/java/io/neow3j/devpack/constants/CallFlags.java
  devpack/src/main/java/io/neow3j/devpack/constants/FindOptions.java
  devpack/src/main/java/io/neow3j/devpack/constants/NamedCurve.java
  devpack/src/main/java/io/neow3j/devpack/constants/OracleResponseCode.java
  devpack/src/main/java/io/neow3j/devpack/constants/Role.java
  devpack/src/main/java/io/neow3j/devpack/constants/TriggerType.java
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractInterface.java
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java
  devpack/src/main/java/io/neow3j/devpack/contracts/FungibleToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/OracleContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/RoleManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/StdLib.java
Labels: maintenance

#558 Fix for bug in negative number handling in ScriptBuilder
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/test/java/io/neow3j/contract/ScriptBuilderTest.java
Labels: bug
