Repository neow3j/neow3j, pull requests merged in 2021-02, with the labels that each got.

#393 Remove callback syscalls
  devpack/src/main/java/io/neow3j/devpack/system/Callback.java
  utils/src/main/java/io/neow3j/constants/InteropServiceCode.java
Labels: devpack, neo3, preview5

#398 NefFile updates
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoInstruction.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  contract/src/test/resources/contracts/DotnetContract.nef
  contract/src/test/resources/contracts/TestContract.cs
  contract/src/test/resources/contracts/TestContract.nef
  contract/src/test/resources/contracts/TestContractWithMethodTokens.cs
  contract/src/test/resources/contracts/TestContractWithMethodTokens.nef
  core/src/main/java/io/neow3j/protocol/core/methods/response/ContractNef.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  model/src/main/java/io/neow3j/model/types/CallFlags.java
  utils/src/main/java/io/neow3j/contract/ScriptReader.java
  utils/src/main/java/io/neow3j/io/BinaryReader.java
  utils/src/main/java/io/neow3j/io/BinaryWriter.java
  utils/src/main/java/io/neow3j/io/IOUtils.java
  utils/src/test/java/io/neow3j/io/BinaryWriterTest.java
Labels: devpack, neo3, preview5

#399 Revert gas notation in RPC methods to integers instead of decimals
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test/resources/responses/calculatenetworkfee.json
  contract/src/test/resources/responses/invokescript_symbol_neo.json
  contract/src/test/resources/responses/invokescript_transfer_with_fixed_sysfee.json
  contract/src/test/resources/responses/management_setMinimumDeploymentFee.json
  contract/src/test/resources/responses/policy_blockAccount.json
  contract/src/test/resources/responses/policy_setExecFeeFactor.json
  contract/src/test/resources/responses/policy_setFeePerByte.json
  contract/src/test/resources/responses/policy_setMaxBlockSize.json
  contract/src/test/resources/responses/policy_setMaxBlockSystemFee.json
  contract/src/test/resources/responses/policy_setMaxTransactionsPerBlock.json
  contract/src/test/resources/responses/policy_setStoragePrice.json
  contract/src/test/resources/responses/policy_unblockAccount.json
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoNetworkFee.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
Labels: neo3, preview5, sdk

#400 Adapt contract calls
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoModule.java
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  compiler/src/test/java/io/neow3j/compiler/MethodTokensTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  contract/src/test/resources/responses/invokefunction_symbol_neo.json
  devpack/src/main/java/io/neow3j/devpack/neo/Contract.java
  utils/src/main/java/io/neow3j/constants/InteropServiceCode.java
  utils/src/main/java/io/neow3j/contract/ScriptBuilder.java
Labels: devpack, neo3, preview5, sdk

#402 Adapt devpack's iterator and enumerator
  compiler/src/test-integration/java/io/neow3j/compiler/EnumeratorTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/IteratorTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerTest.java
  devpack/src/main/java/io/neow3j/devpack/Map.java
  devpack/src/main/java/io/neow3j/devpack/neo/Enumerator.java
  devpack/src/main/java/io/neow3j/devpack/neo/Iterator.java
  devpack/src/main/java/io/neow3j/devpack/neo/Storage.java
  utils/src/main/java/io/neow3j/constants/InteropServiceCode.java
Labels: devpack, neo3, preview5

#374 High Priority Transaction Attribute
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  contract/src/test/resources/responses/getcommittee.json
  core/src/main/java/io/neow3j/protocol/core/methods/response/HighPriorityAttribute.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionAttribute.java
  core/src/main/java/io/neow3j/transaction/HighPriorityAttribute.java
  core/src/main/java/io/neow3j/transaction/TransactionAttributeType.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
Labels: feature, neo3, sdk

#406 Verification method integration tests
  compiler/src/test-integration/java/io/neow3j/compiler/VerificationMethodIntegrationTest.java
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
Labels: devpack, neo3, sdk

#306 Add oracle contract interface to devpack
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  devpack/src/main/java/io/neow3j/devpack/neo/OracleContract.java
Labels: devpack, neo3, preview4

#407 Token Update
  compiler/src/test-integration/java/io/neow3j/compiler/FungibleTokenTest.java
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/ContractUtils.java
  contract/src/main/java/io/neow3j/contract/FungibleToken.java
  contract/src/main/java/io/neow3j/contract/GasToken.java
  contract/src/main/java/io/neow3j/contract/NFToken.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/NeoURI.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/main/java/io/neow3j/contract/PolicyContract.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/main/java/io/neow3j/contract/Token.java
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/NFTokenTest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/resources/responses/nft_ownerof.json
  contract/src/test/resources/responses/nft_properties.json
  contract/src/test/resources/responses/response_invalid_address.json
  contract/src/test/resources/responses/response_stack_integer.json
  core/src/main/java/io/neow3j/protocol/core/methods/response/ByteStringStackItem.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NFTokenProperties.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TokenState.java
  core/src/test/java/io/neow3j/protocol/core/methods/response/StackItemTest.java
  devpack/src/main/java/io/neow3j/devpack/contracts/FungibleToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/GasToken.java
  devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java
Labels: feature, neo3, preview5, sdk

#403 Update management contract
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/DeploymentMethodIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NeoTokenTest.java
  compiler/src/test-integration/resources/node-config/rpcserver.config.json
  compiler/src/test/java/io/neow3j/compiler/DeploymentMethodTest.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/resources/contracts/TestContract.manifest.json
  contract/src/test/resources/responses/management_deploy.json
  core/src/test-integration/resources/node-config/rpcserver.config.json
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/NeoToken.java
Labels: devpack, neo3, preview5, sdk

#416 Fix compiler and compiler tests
  compiler/src/main/java/io/neow3j/compiler/NeoInstruction.java
  compiler/src/main/java/io/neow3j/compiler/NeoModule.java
  compiler/src/test-integration/java/io/neow3j/compiler/PolicyContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/RoleManagementTest.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
Labels: devpack, neo3, preview5

#417 devpack ledger contract
  compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  core/src/main/java/io/neow3j/constants/InteropServiceCode.java
  devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java
  devpack/src/main/java/io/neow3j/devpack/neo/Block.java
  devpack/src/main/java/io/neow3j/devpack/neo/Blockchain.java
Labels: devpack, neo3, preview5

#421 Devpack integer type normalization and package refactor
  compiler/src/test-integration/java/io/neow3j/compiler/BinaryTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractManagementIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/IteratorTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/VerificationMethodIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/AsmHelperTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerTest.java
  compiler/src/test/java/io/neow3j/compiler/ContractNameTest.java
  compiler/src/test/java/io/neow3j/compiler/StringLiteralHelperTest.java
  compiler/src/test/java/io/neow3j/compiler/SupportedStandardsTest.java
  compiler/src/test/java/io/neow3j/compiler/VerificationMethodTest.java
  devpack/src/main/java/io/neow3j/devpack/Account.java
  devpack/src/main/java/io/neow3j/devpack/Binary.java
  devpack/src/main/java/io/neow3j/devpack/Block.java
  devpack/src/main/java/io/neow3j/devpack/CallFlags.java
  devpack/src/main/java/io/neow3j/devpack/Contract.java
  devpack/src/main/java/io/neow3j/devpack/Crypto.java
  devpack/src/main/java/io/neow3j/devpack/ExecutionEngine.java
  devpack/src/main/java/io/neow3j/devpack/Helper.java
  devpack/src/main/java/io/neow3j/devpack/Iterator.java
  devpack/src/main/java/io/neow3j/devpack/Json.java
  devpack/src/main/java/io/neow3j/devpack/Notification.java
  devpack/src/main/java/io/neow3j/devpack/OracleContract.java
  devpack/src/main/java/io/neow3j/devpack/Runtime.java
  devpack/src/main/java/io/neow3j/devpack/Storage.java
  devpack/src/main/java/io/neow3j/devpack/StorageContext.java
  devpack/src/main/java/io/neow3j/devpack/StorageFlag.java
  devpack/src/main/java/io/neow3j/devpack/StorageMap.java
  devpack/src/main/java/io/neow3j/devpack/Transaction.java
  devpack/src/main/java/io/neow3j/devpack/TriggerType.java
  devpack/src/main/java/io/neow3j/devpack/annotations/ContractHash.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Group.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Instruction.java
  devpack/src/main/java/io/neow3j/devpack/annotations/ManifestExtra.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Permission.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Syscall.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Trust.java
  devpack/src/main/java/io/neow3j/devpack/contracts/ContractManagement.java
  devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java
  devpack/src/main/java/io/neow3j/devpack/contracts/PolicyContract.java
  devpack/src/main/java/io/neow3j/devpack/system/SyscallCallback.java
Labels: devpack, maintenance, neo3

#422 Convenience Method for Array ContractParameter
  core/src/main/java/io/neow3j/contract/ContractParameter.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
Labels: feature, neo3, sdk

#423 Data parameter in transfers
  contract/src/main/java/io/neow3j/contract/ContractManagement.java
  contract/src/main/java/io/neow3j/contract/FungibleToken.java
  contract/src/main/java/io/neow3j/contract/NeoToken.java
  contract/src/main/java/io/neow3j/contract/NonFungibleToken.java
  contract/src/main/java/io/neow3j/contract/RoleManagement.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/main/java/io/neow3j/contract/exceptions/InvocationConfigurationException.java
  contract/src/main/java/io/neow3j/contract/exceptions/UnexpectedReturnTypeException.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/ContractTestHelper.java
  contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/NeoURITest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/java/io/neow3j/contract/RoleManagementTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TokenTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
Labels: feature, neo3, sdk

#425 Get contract state by name
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/core/Neo.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/RequestTest.java
Labels: feature, neo3, preview5, sdk

#424 'specific contract method' annotations
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/NeoModule.java
  compiler/src/test/java/io/neow3j/compiler/DeploymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP11PaymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP17PaymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/VerificationMethodTest.java
  devpack/src/main/java/io/neow3j/devpack/annotations/MethodSignature.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnDeployment.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP11Payment.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnNEP17Payment.java
  devpack/src/main/java/io/neow3j/devpack/annotations/OnVerification.java
Labels: devpack, feature, neo3

#426 Use magic number from `getversion` for NeoConfig
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/PolicyContractTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/model/NeoConfig.java
  core/src/main/java/io/neow3j/protocol/Neow3j.java
  core/src/main/java/io/neow3j/protocol/core/JsonRpc2_0Neow3j.java
  core/src/main/java/io/neow3j/protocol/core/Neo.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/NeoGetVersion.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/utils/AddressUtils.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
  core/src/test/java/io/neow3j/utils/AddressUtilsTest.java
Labels: neo3, sdk

#418 Oracle contract for devpack
  compiler/build.gradle
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/OracleContractTest.java
  compiler/src/test-integration/resources/node-config/oracle.config.json
  contract/src/test/java/io/neow3j/contract/GasTokenTest.java
  core/build.gradle
  core/src/main/java/io/neow3j/protocol/core/methods/response/OracleResponseAttribute.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/OracleResponseCode.java
  core/src/main/java/io/neow3j/protocol/core/methods/response/TransactionAttribute.java
  core/src/main/java/io/neow3j/transaction/TransactionAttributeType.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  devpack/src/main/java/io/neow3j/devpack/Iterator.java
  devpack/src/main/java/io/neow3j/devpack/OracleContract.java
Labels: devpack, neo3

#430 Changes in transaction signing to allow "signing" with a smart contract
  contract/src/main/java/io/neow3j/contract/TransactionBuilder.java
  contract/src/test/java/io/neow3j/contract/TransactionBuilderTest.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/Witness.java
  core/src/main/java/io/neow3j/wallet/Account.java
  core/src/main/java/io/neow3j/wallet/Wallet.java
  core/src/test/java/io/neow3j/wallet/AccountTest.java
  core/src/test/java/io/neow3j/wallet/WalletTest.java
Labels: feature, neo3, sdk

#435 Prohibit local variables in static constructor
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/CompilerException.java
  compiler/src/main/java/io/neow3j/compiler/InitsslotNeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
Labels: devpack, neo3
