Repository neow3j/neow3j, pull requests merged in 2022-03, with the labels that each got.

#730 Additions to neow3j's Transaction class
  compiler/src/test/java/io/neow3j/compiler/ListTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP11PaymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP17PaymentMethodTest.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/script/InvocationScript.java
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/main/java/io/neow3j/transaction/ContractParametersContext.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
  core/src/test/java/io/neow3j/crypto/ECKeyPairTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/transaction/InvocationScriptTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
Labels: feature, sdk

#731 Ensure correct ordering of signatures
  contract/src/test-integration/java/io/neow3j/contract/FungibleTokenIntegrationTest.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/main/java/io/neow3j/script/VerificationScript.java
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/Witness.java
  core/src/main/java/io/neow3j/wallet/Account.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
Labels: sdk

#735 Fix for isEvent method
  build.gradle
  compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/InitsslotNeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/ContractEventsIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/ContractEventsTest.java
Labels: bug, devpack

#739 Add utility method for byte ContractParameter
  .idea/codeStyles/Project.xml
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
Labels: feature, devpack, dev-wishlist

#738 Support instance inheritance
  compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/SuperNeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/InstanceInheritanceIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/MapTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/NullCheckIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ObjectsTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StaticVariablesIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/StdLibIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/StaticVariablesTest.java
  compiler/src/test/java/io/neow3j/compiler/sourcelookup/DirectorySourceContainerTest.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Struct.java
Labels: feature
