Repository neow3j/neow3j, pull requests merged in 2022-01, with the labels that each got.

#705 Correct multi-sig script creation
  contract/src/main/java/io/neow3j/contract/NeoNameService.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/main/java/io/neow3j/script/VerificationScript.java
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/main/java/io/neow3j/types/Hash160.java
  core/src/test/java/io/neow3j/contract/Hash160Test.java
  core/src/test/java/io/neow3j/contract/ScriptBuilderTest.java
  core/src/test/java/io/neow3j/crypto/ECKeyPairTest.java
  core/src/test/java/io/neow3j/transaction/VerificationScriptTest.java
  core/src/test/java/io/neow3j/transaction/WitnessTest.java
Labels: bug, sdk

#708 Allow empty array contract parameter
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
  core/src/test/java/io/neow3j/contract/ScriptBuilderTest.java
Labels: sdk, dev-wishlist

#709 Hash and ECPoint improvements
  compiler/src/test-integration/java/io/neow3j/compiler/ByteStringIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/ManifestExtraTest.java
  core/src/main/java/io/neow3j/script/OpCode.java
  devpack/src/main/java/io/neow3j/devpack/ByteString.java
  devpack/src/main/java/io/neow3j/devpack/ECPoint.java
  devpack/src/main/java/io/neow3j/devpack/Hash160.java
  devpack/src/main/java/io/neow3j/devpack/Hash256.java
Labels: feature, devpack, maintenance

#710 Replace ExpectedException with Assert.assertThrows
  build.gradle
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  compiler/src/test/java/io/neow3j/compiler/DeploymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/InstanceVariablesTest.java
  compiler/src/test/java/io/neow3j/compiler/ObjectInheritanceTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP11PaymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/OnNEP17PaymentMethodTest.java
  compiler/src/test/java/io/neow3j/compiler/PermissionManifestTest.java
  compiler/src/test/java/io/neow3j/compiler/StringLiteralHelperTest.java
  compiler/src/test/java/io/neow3j/compiler/TrustManifestTest.java
  compiler/src/test/java/io/neow3j/compiler/VerificationMethodTest.java
  contract/src/test/java/io/neow3j/contract/ContractManagementTest.java
  contract/src/test/java/io/neow3j/contract/FungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  contract/src/test/java/io/neow3j/contract/NeoNameServiceTest.java
  contract/src/test/java/io/neow3j/contract/NeoTokenTest.java
  contract/src/test/java/io/neow3j/contract/NeoURITest.java
  contract/src/test/java/io/neow3j/contract/NonFungibleTokenTest.java
  contract/src/test/java/io/neow3j/contract/RoleManagementTest.java
  contract/src/test/java/io/neow3j/contract/SmartContractTest.java
  contract/src/test/java/io/neow3j/contract/TokenTest.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
  core/src/test/java/io/neow3j/contract/Hash160Test.java
  core/src/test/java/io/neow3j/contract/Hash256Test.java
  core/src/test/java/io/neow3j/crypto/Base58DecodeTest.java
  core/src/test/java/io/neow3j/crypto/SignTest.java
  core/src/test/java/io/neow3j/crypto/WIFTest.java
  core/src/test/java/io/neow3j/protocol/core/JsonRpc2_0Neow3jTest.java
  core/src/test/java/io/neow3j/protocol/core/stackitem/StackItemTest.java
  core/src/test/java/io/neow3j/serialization/BinaryReaderTest.java
  core/src/test/java/io/neow3j/transaction/SignerTest.java
  core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
  core/src/test/java/io/neow3j/transaction/TransactionTest.java
  core/src/test/java/io/neow3j/transaction/WitnessScopeTest.java
  core/src/test/java/io/neow3j/utils/AddressUtilsTest.java
  core/src/test/java/io/neow3j/utils/ArrayUtilsTest.java
  core/src/test/java/io/neow3j/utils/NumericTest.java
  core/src/test/java/io/neow3j/wallet/AccountTest.java
  core/src/test/java/io/neow3j/wallet/WalletTest.java
Labels: maintenance

#712 Support find in StorageMap
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
  devpack/src/main/java/io/neow3j/devpack/StorageMap.java
Labels: devpack

#713 Support nested Map and List Objects in ContractParameter
  core/src/main/java/io/neow3j/types/ContractParameter.java
  core/src/test/java/io/neow3j/contract/ContractParameterTest.java
Labels: feature, sdk
