Repository neow3j/neow3j, pull requests merged in 2022-02, with the labels that each got.

#716 Add NeoStandards enum for SupportedStandards annotation
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/test/java/io/neow3j/compiler/SupportedStandardsTest.java
  devpack/src/main/java/io/neow3j/devpack/annotations/SupportedStandard.java
  devpack/src/main/java/io/neow3j/devpack/annotations/SupportedStandards.java
  devpack/src/main/java/io/neow3j/devpack/constants/NativeContract.java
  devpack/src/main/java/io/neow3j/devpack/constants/NeoStandard.java
Labels: devpack

#720 Extend classes supported in `instanceof`
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/InstanceOfIntegrationTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
Labels: devpack, maintenance

#722 Add project-based code styles file
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  neow3j_code_style_scheme.xml
Labels: maintenance

#721 Add utility methods to create and add groups to manifest
  compiler/src/main/java/io/neow3j/compiler/ManifestBuilder.java
  compiler/src/test-integration/java/io/neow3j/compiler/StorageMapIntegrationTest.java
  contract/src/main/java/io/neow3j/contract/SmartContract.java
  contract/src/test/java/io/neow3j/contract/ContractUtilsTest.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/protocol/core/response/ContractManifest.java
  core/src/main/java/io/neow3j/script/ScriptBuilder.java
  core/src/main/java/io/neow3j/utils/Numeric.java
  core/src/test/java/io/neow3j/crypto/ECKeyPairTest.java
  core/src/test/java/io/neow3j/protocol/core/response/ContractManifestTest.java
  core/src/test/java/io/neow3j/protocol/http/HttpServiceTest.java
Labels: feature, sdk

#724 Add additional system fee method to TransactionBuilder
  core/src/main/java/io/neow3j/transaction/Transaction.java
  core/src/main/java/io/neow3j/transaction/TransactionBuilder.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/TransactionBuilderIntegrationTest.java
  core/src/test/java/io/neow3j/transaction/TransactionBuilderTest.java
Labels: feature, sdk
