Repository neow3j/neow3j, pull requests merged in 2022-04, with the labels that each got.

#745 Minor changes the inheritance code
  compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/SuperNeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  devpack/src/main/java/io/neow3j/devpack/annotations/Struct.java
Labels: maintenance

#752 Add support for NeoVM's ASSERT
  compiler/src/main/java/io/neow3j/compiler/NeoMethod.java
  compiler/src/main/java/io/neow3j/compiler/converters/JumpsConverter.java
  compiler/src/main/java/io/neow3j/compiler/converters/ObjectsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/AssertionIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/ECPointIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/HashIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/TryCatchBlocksTest.java
  compiler/src/test/java/io/neow3j/compiler/AssertionTest.java
  compiler/src/test/java/io/neow3j/compiler/CompilerExceptionsTest.java
  compiler/src/test/java/io/neow3j/compiler/ThrowExceptionTest.java
  core/src/main/java/io/neow3j/script/OpCode.java
Labels: feature, devpack, maintenance

#755 Add field source to ContractNef
  compiler/src/main/java/io/neow3j/compiler/Compiler.java
  contract/src/main/java/io/neow3j/contract/NefFile.java
  contract/src/test/java/io/neow3j/contract/NefFileTest.java
  core/src/main/java/io/neow3j/protocol/core/response/ContractNef.java
  core/src/main/java/io/neow3j/protocol/core/response/ContractState.java
  core/src/main/java/io/neow3j/protocol/core/response/NativeContractState.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jWriteIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  test-tools/src/main/java/io/neow3j/test/NeoTestContainer.java
Labels: bug

#761 Fix handling of branch number in string switch-case compilation
  compiler/src/main/java/io/neow3j/compiler/converters/MethodsConverter.java
  compiler/src/test-integration/java/io/neow3j/compiler/SwitchCaseIntegrationTest.java
Labels: bug, devpack

#762 Fix bug when in compilation of Event without any arguments
  compiler/src/main/java/io/neow3j/compiler/AsmHelper.java
  compiler/src/test/java/io/neow3j/compiler/ContractEventsTest.java
  devpack/src/main/java/io/neow3j/devpack/events/Event0Arg.java
Labels: bug, devpack

#749 Upgrade devpack-test fast-forward methods
  devpack-test/src/main/java/io/neow3j/test/ContractTestExtension.java
  devpack-test/src/test-integration/java/io/neow3j/test/ModuleTest.java
  test-tools/src/main/java/io/neow3j/test/NeoExpressTestContainer.java
  test-tools/src/main/java/io/neow3j/test/TestBlockchain.java
  test-tools/src/main/resources/test.properties
Labels: feature

#758 Neo 3.2.0/1 updates
  compiler/src/test-integration/java/io/neow3j/compiler/ContractTestRule.java
  compiler/src/test-integration/java/io/neow3j/compiler/CryptoLibIntegrationTest.java
  compiler/src/test-integration/java/io/neow3j/compiler/LedgerContractIntegrationTest.java
  core/src/main/java/io/neow3j/constants/NeoConstants.java
  core/src/main/java/io/neow3j/crypto/ECKeyPair.java
  core/src/main/java/io/neow3j/protocol/core/response/NeoApplicationLog.java
  core/src/main/java/io/neow3j/protocol/core/response/TransactionSigner.java
  core/src/main/java/io/neow3j/protocol/core/stackitem/ArrayStackItem.java
  core/src/main/java/io/neow3j/protocol/core/stackitem/ListLikeStackItem.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/AndCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/BooleanCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/CalledByContractCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/CalledByEntryCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/CalledByGroupCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/CompositeCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/GroupCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/GroupTypeCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/NotCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/OrCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/ScriptHashCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/ScriptHashTypeCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/WitnessCondition.java
  core/src/main/java/io/neow3j/protocol/core/witnessrule/WitnessRule.java
  core/src/main/java/io/neow3j/protocol/exceptions/WitnessConditionCastException.java
  core/src/main/java/io/neow3j/transaction/Signer.java
  core/src/main/java/io/neow3j/transaction/WitnessScope.java
  core/src/main/java/io/neow3j/transaction/witnessrule/AndCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/BooleanCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/CalledByContractCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/CalledByEntryCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/CalledByGroupCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/CompositeCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/GroupCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/GroupTypeCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/NotCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/OrCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/ScriptHashCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/ScriptHashTypeCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/WitnessAction.java
  core/src/main/java/io/neow3j/transaction/witnessrule/WitnessCondition.java
  core/src/main/java/io/neow3j/transaction/witnessrule/WitnessConditionType.java
  core/src/main/java/io/neow3j/transaction/witnessrule/WitnessRule.java
  core/src/main/java/io/neow3j/types/NeoVMStateType.java
  core/src/test-integration/java/io/neow3j/protocol/Neow3jReadOnlyIntegrationTest.java
  core/src/test-integration/java/io/neow3j/protocol/TransactionBuilderIntegrationTest.java
  core/src/test/java/io/neow3j/protocol/core/RequestTest.java
  core/src/test/java/io/neow3j/protocol/core/ResponseTest.java
  core/src/test/java/io/neow3j/protocol/core/witnessrule/WitnessRuleTest.java
  core/src/test/java/io/neow3j/transaction/SignerTest.java
  core/src/test/java/io/neow3j/transaction/witnessrule/WitnessConditionTest.java
  core/src/test/java/io/neow3j/types/NeoVMStateTypeTest.java
  devpack/src/main/java/io/neow3j/devpack/constants/VMState.java
  devpack/src/main/java/io/neow3j/devpack/contracts/CryptoLib.java
  devpack/src/main/java/io/neow3j/devpack/contracts/LedgerContract.java
  test-tools/src/main/resources/test.properties
Labels: Neo 3.2.1

#765 Release 3.17.0
  README.md
Labels: Neo 3.2.1
